
FROM freesurfer-base:7.4.1

LABEL maintainer="freesurfer R package developers" \
      description="FreeSurfer with R and littler installed for R package management. R is configured to use Posit Package Manager for packages. This image is primarily used for building and testing R packages that depend on FreeSurfer, and includes pandoc, devtools, and pak."

## Now install R and littler, and create a link for littler in /usr/local/bin
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gnupg \
        libcurl4-openssl-dev \
        qpdf \
        pandoc \
        pandoc-citeproc \
		fonts-texgyre \
        libopenblas0-pthread \
		littler \
        r-cran-docopt \
        r-cran-littler \
		r-base \
		r-base-dev \
        r-base-core \
		r-recommended \
	&& chown root:staff "/usr/local/lib/R/site-library" \
	&& chmod g+ws "/usr/local/lib/R/site-library" \
	&& ln -s /usr/lib/R/site-library/littler/examples/install.r /usr/local/bin/install.r \
	&& ln -s /usr/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r \
	&& ln -s /usr/lib/R/site-library/littler/examples/installBioc.r /usr/local/bin/installBioc.r \
	&& ln -s /usr/lib/R/site-library/littler/examples/installDeps.r /usr/local/bin/installDeps.r \
	&& ln -s /usr/lib/R/site-library/littler/examples/installGithub.r /usr/local/bin/installGithub.r \
	&& ln -s /usr/lib/R/site-library/littler/examples/testInstalled.r /usr/local/bin/testInstalled.r \
	&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
	&& rm -rf /var/lib/apt/lists/*

RUN echo 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"))' >> $(R RHOME)/etc/Rprofile.site \
    && Rscript -e \
        "install.packages(c('pak')); \
        pak::pkg_install('devtools')"

CMD ["bash"]
